### ISSUE TITLE
Is it possible to run 2D Delaunay Triangulation on GPU using this library (simple DT not alpha shape)

### ISSUE THREAD

**Issue by YuxinxinChen** [ashwin/gAlpha2D#3]
Hi gAlpha2D team,

I would like to run 2D Delaunay Triangulation on GPU (prefer CUDA) given a set of vertices or an arbitrary triangulation. No quality of triangles is required but only Delaunay. Is it possible to run it using your library?

I am also wondering which algorithm you use for Delaunay Triangulation, Lawson's based algorithm, or Voronoi based algorithm?

Thanks a lot!

Yuxin

**Comment by ashwin** [comment]
@YuxinxinChen Please see my responses to: https://github.com/ashwin/gDel3D/issues/12
